export enum NIS2Category {
  RISK_ANALYSIS = 'RISK_ANALYSIS',
  INCIDENT_HANDLING = 'INCIDENT_HANDLING',
  BUSINESS_CONTINUITY = 'BUSINESS_CONTINUITY',
  SUPPLY_CHAIN = 'SUPPLY_CHAIN',
  NETWORK_SECURITY = 'NETWORK_SECURITY',
  VULNERABILITY_MANAGEMENT = 'VULNERABILITY_MANAGEMENT',
  CYBER_HYGIENE = 'CYBER_HYGIENE',
  CRYPTOGRAPHY = 'CRYPTOGRAPHY',
  ACCESS_CONTROL = 'ACCESS_CONTROL',
  ASSET_MANAGEMENT = 'ASSET_MANAGEMENT',
}

export interface NIS2Question {
  id: string;
  category: NIS2Category;
  question: string;
  description: string;
  options: { value: number; label: string }[];
  weight: number;
}

export const NIS2_CATEGORY_LABELS: Record<NIS2Category, string> = {
  [NIS2Category.RISK_ANALYSIS]: 'Analyse de risques',
  [NIS2Category.INCIDENT_HANDLING]: 'Gestion des incidents',
  [NIS2Category.BUSINESS_CONTINUITY]: 'Continuité d\'activité',
  [NIS2Category.SUPPLY_CHAIN]: 'Chaîne d\'approvisionnement',
  [NIS2Category.NETWORK_SECURITY]: 'Sécurité réseau',
  [NIS2Category.VULNERABILITY_MANAGEMENT]: 'Gestion des vulnérabilités',
  [NIS2Category.CYBER_HYGIENE]: 'Cyber-hygiène & formation',
  [NIS2Category.CRYPTOGRAPHY]: 'Cryptographie',
  [NIS2Category.ACCESS_CONTROL]: 'Contrôle d\'accès',
  [NIS2Category.ASSET_MANAGEMENT]: 'Gestion des actifs',
};

export const NIS2_QUESTIONS: NIS2Question[] = [
  {
    id: 'ra-1',
    category: NIS2Category.RISK_ANALYSIS,
    question: 'Avez-vous réalisé une analyse de risques cybersécurité au cours des 12 derniers mois ?',
    description: 'L\'article 21.2.a de NIS2 exige une politique d\'analyse des risques.',
    options: [
      { value: 0, label: 'Non, aucune analyse de risques réalisée' },
      { value: 1, label: 'Une analyse informelle a été faite' },
      { value: 2, label: 'Une analyse formelle existe mais n\'est pas régulièrement mise à jour' },
      { value: 3, label: 'Une analyse formelle est réalisée et mise à jour au moins annuellement' },
    ],
    weight: 3,
  },
  {
    id: 'ra-2',
    category: NIS2Category.RISK_ANALYSIS,
    question: 'Disposez-vous d\'un registre des actifs informatiques critiques ?',
    description: 'Identification et classification des systèmes et données essentiels.',
    options: [
      { value: 0, label: 'Non, nous n\'avons pas de registre' },
      { value: 1, label: 'Nous avons une liste partielle et informelle' },
      { value: 2, label: 'Un registre existe mais n\'est pas maintenu régulièrement' },
      { value: 3, label: 'Un registre complet est maintenu et mis à jour régulièrement' },
    ],
    weight: 2,
  },
  {
    id: 'ih-1',
    category: NIS2Category.INCIDENT_HANDLING,
    question: 'Avez-vous un plan de réponse aux incidents de cybersécurité ?',
    description: 'NIS2 impose la gestion des incidents, incluant la prévention, la détection et la réponse.',
    options: [
      { value: 0, label: 'Non, aucun plan défini' },
      { value: 1, label: 'Des procédures informelles existent' },
      { value: 2, label: 'Un plan existe mais n\'a jamais été testé' },
      { value: 3, label: 'Un plan documenté existe et est testé régulièrement' },
    ],
    weight: 3,
  },
  {
    id: 'ih-2',
    category: NIS2Category.INCIDENT_HANDLING,
    question: 'Êtes-vous en mesure de notifier un incident cyber aux autorités sous 24h ?',
    description: 'NIS2 exige une notification initiale à l\'ANSSI sous 24h.',
    options: [
      { value: 0, label: 'Non, nous ne savons pas comment faire' },
      { value: 1, label: 'Nous connaissons la procédure mais elle n\'est pas formalisée' },
      { value: 2, label: 'La procédure est documentée mais les contacts ne sont pas identifiés' },
      { value: 3, label: 'Procédure documentée, contacts identifiés et équipe formée' },
    ],
    weight: 3,
  },
  {
    id: 'bc-1',
    category: NIS2Category.BUSINESS_CONTINUITY,
    question: 'Disposez-vous d\'un plan de continuité d\'activité (PCA) en cas de cyberattaque ?',
    description: 'Capacité à maintenir les activités essentielles pendant et après un incident.',
    options: [
      { value: 0, label: 'Non, aucun PCA' },
      { value: 1, label: 'Des procédures de base existent (sauvegardes)' },
      { value: 2, label: 'Un PCA existe mais n\'a pas été testé récemment' },
      { value: 3, label: 'Un PCA complet est documenté, testé et mis à jour annuellement' },
    ],
    weight: 3,
  },
  {
    id: 'bc-2',
    category: NIS2Category.BUSINESS_CONTINUITY,
    question: 'Vos sauvegardes sont-elles chiffrées et stockées hors-ligne ?',
    description: 'Protection des sauvegardes contre les ransomwares.',
    options: [
      { value: 0, label: 'Pas de sauvegardes régulières' },
      { value: 1, label: 'Sauvegardes en ligne uniquement' },
      { value: 2, label: 'Sauvegardes hors-ligne mais non chiffrées' },
      { value: 3, label: 'Sauvegardes chiffrées, hors-ligne, avec tests de restauration réguliers' },
    ],
    weight: 2,
  },
  {
    id: 'sc-1',
    category: NIS2Category.SUPPLY_CHAIN,
    question: 'Évaluez-vous la sécurité de vos fournisseurs et prestataires IT ?',
    description: 'NIS2 impose la sécurité de la chaîne d\'approvisionnement.',
    options: [
      { value: 0, label: 'Non, aucune évaluation' },
      { value: 1, label: 'Évaluation informelle pour certains fournisseurs critiques' },
      { value: 2, label: 'Clauses de sécurité dans les contrats mais pas de suivi' },
      { value: 3, label: 'Évaluation systématique, clauses contractuelles et audits réguliers' },
    ],
    weight: 2,
  },
  {
    id: 'sc-2',
    category: NIS2Category.SUPPLY_CHAIN,
    question: 'Avez-vous une liste de vos fournisseurs ayant accès à vos systèmes ou données ?',
    description: 'Visibilité sur les tiers ayant des accès à votre infrastructure.',
    options: [
      { value: 0, label: 'Non, pas de liste' },
      { value: 1, label: 'Liste partielle et informelle' },
      { value: 2, label: 'Liste complète mais sans revue des accès' },
      { value: 3, label: 'Liste complète avec revue trimestrielle des accès' },
    ],
    weight: 2,
  },
  {
    id: 'ns-1',
    category: NIS2Category.NETWORK_SECURITY,
    question: 'Votre réseau est-il segmenté (séparation des environnements critiques) ?',
    description: 'Sécurité dans l\'acquisition et la maintenance des réseaux.',
    options: [
      { value: 0, label: 'Non, réseau plat sans segmentation' },
      { value: 1, label: 'Segmentation basique (WiFi invité séparé)' },
      { value: 2, label: 'Segmentation par VLAN mais sans contrôle d\'accès entre segments' },
      { value: 3, label: 'Segmentation complète avec pare-feu inter-segments et monitoring' },
    ],
    weight: 2,
  },
  {
    id: 'ns-2',
    category: NIS2Category.NETWORK_SECURITY,
    question: 'Utilisez-vous un pare-feu et un système de détection d\'intrusion ?',
    description: 'Protection périmétrique et détection des menaces réseau.',
    options: [
      { value: 0, label: 'Non, pas de pare-feu dédié' },
      { value: 1, label: 'Pare-feu basique (box opérateur)' },
      { value: 2, label: 'Pare-feu professionnel mais sans IDS/IPS' },
      { value: 3, label: 'Pare-feu next-gen avec IDS/IPS et journalisation centralisée' },
    ],
    weight: 2,
  },
  {
    id: 'vm-1',
    category: NIS2Category.VULNERABILITY_MANAGEMENT,
    question: 'Appliquez-vous les mises à jour de sécurité dans un délai défini ?',
    description: 'Gestion et divulgation des vulnérabilités.',
    options: [
      { value: 0, label: 'Pas de politique de mise à jour' },
      { value: 1, label: 'Mises à jour appliquées quand on y pense' },
      { value: 2, label: 'Mises à jour mensuelles mais sans priorisation' },
      { value: 3, label: 'Mises à jour critiques sous 48h, politique documentée' },
    ],
    weight: 2,
  },
  {
    id: 'vm-2',
    category: NIS2Category.VULNERABILITY_MANAGEMENT,
    question: 'Réalisez-vous des scans de vulnérabilités ou des tests d\'intrusion ?',
    description: 'Détection proactive des failles de sécurité.',
    options: [
      { value: 0, label: 'Jamais' },
      { value: 1, label: 'Ponctuellement, sans régularité' },
      { value: 2, label: 'Scans automatisés réguliers mais pas de pentest' },
      { value: 3, label: 'Scans automatisés + pentest annuel par un tiers qualifié' },
    ],
    weight: 2,
  },
  {
    id: 'ch-1',
    category: NIS2Category.CYBER_HYGIENE,
    question: 'Vos employés reçoivent-ils une formation cybersécurité régulière ?',
    description: 'Pratiques de cyber-hygiène et formation à la cybersécurité.',
    options: [
      { value: 0, label: 'Non, aucune formation' },
      { value: 1, label: 'Formation ponctuelle à l\'embauche uniquement' },
      { value: 2, label: 'Formation annuelle obligatoire' },
      { value: 3, label: 'Formation continue avec simulations de phishing et suivi individuel' },
    ],
    weight: 3,
  },
  {
    id: 'ch-2',
    category: NIS2Category.CYBER_HYGIENE,
    question: 'Avez-vous une politique de mots de passe et d\'authentification forte ?',
    description: 'Règles de complexité et authentification multi-facteur.',
    options: [
      { value: 0, label: 'Pas de politique de mots de passe' },
      { value: 1, label: 'Politique basique (longueur minimale)' },
      { value: 2, label: 'Politique stricte mais MFA non généralisé' },
      { value: 3, label: 'Politique stricte + MFA obligatoire sur tous les systèmes critiques' },
    ],
    weight: 3,
  },
  {
    id: 'cr-1',
    category: NIS2Category.CRYPTOGRAPHY,
    question: 'Vos données sensibles sont-elles chiffrées au repos et en transit ?',
    description: 'Politiques relatives à l\'utilisation de la cryptographie.',
    options: [
      { value: 0, label: 'Pas de chiffrement' },
      { value: 1, label: 'HTTPS en place mais données non chiffrées au repos' },
      { value: 2, label: 'Chiffrement en transit (TLS) et partiel au repos' },
      { value: 3, label: 'Chiffrement systématique en transit et au repos, gestion des clés documentée' },
    ],
    weight: 2,
  },
  {
    id: 'cr-2',
    category: NIS2Category.CRYPTOGRAPHY,
    question: 'Gérez-vous vos certificats et clés de chiffrement de manière centralisée ?',
    description: 'Gestion du cycle de vie des certificats.',
    options: [
      { value: 0, label: 'Non, pas de gestion centralisée' },
      { value: 1, label: 'Gestion manuelle avec tableur' },
      { value: 2, label: 'Outil de gestion en place mais renouvellement manuel' },
      { value: 3, label: 'Gestion centralisée avec renouvellement automatique' },
    ],
    weight: 1,
  },
  {
    id: 'ac-1',
    category: NIS2Category.ACCESS_CONTROL,
    question: 'Appliquez-vous le principe du moindre privilège pour les accès ?',
    description: 'Politiques de contrôle d\'accès et gestion des actifs.',
    options: [
      { value: 0, label: 'Non, les employés ont des accès larges par défaut' },
      { value: 1, label: 'Les accès admin sont limités mais les accès utilisateurs sont larges' },
      { value: 2, label: 'Accès basés sur les rôles mais sans revue régulière' },
      { value: 3, label: 'RBAC strict avec revue trimestrielle et désactivation automatique au départ' },
    ],
    weight: 2,
  },
  {
    id: 'ac-2',
    category: NIS2Category.ACCESS_CONTROL,
    question: 'Avez-vous un processus de gestion des arrivées/départs ?',
    description: 'Création et suppression des comptes lors des mouvements de personnel.',
    options: [
      { value: 0, label: 'Non, pas de processus défini' },
      { value: 1, label: 'Processus informel' },
      { value: 2, label: 'Processus documenté mais pas toujours suivi' },
      { value: 3, label: 'Processus automatisé avec checklist et vérification systématique' },
    ],
    weight: 2,
  },
  {
    id: 'am-1',
    category: NIS2Category.ASSET_MANAGEMENT,
    question: 'Utilisez-vous des solutions EDR/XDR sur les postes de travail ?',
    description: 'Solutions de détection et réponse sur les endpoints.',
    options: [
      { value: 0, label: 'Non, antivirus basique ou aucun' },
      { value: 1, label: 'Antivirus professionnel mais pas d\'EDR' },
      { value: 2, label: 'EDR déployé mais sans monitoring actif' },
      { value: 3, label: 'EDR/XDR avec monitoring 24/7 et réponse automatisée' },
    ],
    weight: 2,
  },
  {
    id: 'am-2',
    category: NIS2Category.ASSET_MANAGEMENT,
    question: 'Vos communications internes sensibles sont-elles sécurisées ?',
    description: 'Communications sécurisées, y compris en situation d\'urgence.',
    options: [
      { value: 0, label: 'Utilisation de messageries grand public sans contrôle' },
      { value: 1, label: 'Messagerie d\'entreprise mais sans politique de sécurité' },
      { value: 2, label: 'Messagerie chiffrée avec politique d\'usage' },
      { value: 3, label: 'Messagerie chiffrée, canaux d\'urgence dédiés, communications de crise testées' },
    ],
    weight: 1,
  },
];
