spring:
  jpa:
    show-sql: false

ai-security:
  security:
    bypass: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    io.cybersensei: INFO
    org.springframework.security: WARN
